### ISSUE TITLE
Make redis address configurable

### ISSUE THREAD

**Issue by kpcyrd** [LibreRead/server#12]
Redis is currently hardcoded to `localhost:6379`. This should be configurable based on an environment variable (that can default to `localhost:6379`).

**Comment by mysticmode** [comment]
https://github.com/LibreRead/server/blob/3a0d8cdd4f37f8d2515ec3e1ad09694ccf29db61/server.go#L63
https://github.com/LibreRead/server/blob/3a0d8cdd4f37f8d2515ec3e1ad09694ccf29db61/server.go#L192-L201

is this fine?

**Comment by kpcyrd** [comment]
Something like this might be useful for other things that have defaults but might be configurable :)

```go
func getEnv(key, fallback string) string {
    if value, ok := os.LookupEnv(key); ok {
        return value
    }
    return fallback
}
```
https://stackoverflow.com/a/40326580

Your code should work fine for my usecase though!

**Comment by kpcyrd** [comment]
Fixed in 7823e4af7012b978a1f71ffa43d3939bcaef4a6c

**Comment by mysticmode** [comment]
I have changed it here
https://github.com/LibreRead/server/blob/f9874dac236b7a1a528249c24523c0788d52c920/server.go#L194
https://github.com/LibreRead/server/blob/f9874dac236b7a1a528249c24523c0788d52c920/server.go#L263-L268

**Comment by mysticmode** [comment]
That function needs to updated on all the places where we use Env variables. I will do this tomorow.

Thanks for this good suggestion :)
