### ISSUE TITLE
Ensure upload folders exists

### ISSUE THREAD

**Issue by kpcyrd** [LibreRead/server#13]
I ran into a problem with uploads not being saved correctly. It seems the folders `./uploads/` and `./uploads/img/` are expected to exist, but aren't created by the application when they don't. The application could try to create those folders if they don't exist yet before writing uploads. The upload was considered successful regardless, this could be improved by an upload error.

**Comment by mysticmode** [comment]
Ah, this is an issue. yes, Thank you.

I have created this for install but forgot to do for the development environment.
https://github.com/LibreRead/install/tree/master/uploads/img

I'll fix this now.

**Comment by mysticmode** [comment]
Hey, Could you check this?
https://github.com/LibreRead/server/blob/f9874dac236b7a1a528249c24523c0788d52c920/server.go#L199-L203

**Comment by kpcyrd** [comment]
I'd prefer if the permissions for that folder are 0755 instead of 0777, which would make that folder world-writable.

**Comment by mysticmode** [comment]
Done
https://github.com/LibreRead/server/blob/1a8049680d55aa88ac120dabd573813f341b2b86/server.go#L202

**Comment by mysticmode** [comment]
@kpcyrd is it possible for you come to Discord?. Need to chat with you for few minutes :)

https://discord.gg/wHCM7DZ
