### ISSUE TITLE
musl vs glibc?

### ISSUE THREAD

**Issue by muhahacz** [LibreRead/server#21]
Hello, thanks for a great piece of software.
I have question .. 
Server binary from https://github.com/LibreRead/install/blob/master/server is compiled agains glibc? Because i can not get it work in alpine, but it works after i add glibc package.  ( https://github.com/sgerrand/alpine-pkg-glibc )
Thanks

**Comment by kpcyrd** [comment]
```
$ ldd server
ldd: warning: you do not have execution permission for `./server'
	linux-vdso.so.1 (0x0000679f6ea98000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x0000679f6e672000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x0000679f6e454000)
	libc.so.6 => /usr/lib/libc.so.6 (0x0000679f6e09c000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x0000679f6e876000)
$
```
The precompiled binary is indeed linked against glibc. The [docker image][0] is using musl just fine though, so I would recommend building from source.

[0]: https://github.com/LibreRead/server/blob/master/Dockerfile
