### ISSUE TITLE
Broken cover images in collection view

### ISSUE THREAD

**Issue by jamesscottbrown** [LibreRead/server#3]
When viewing details of a collection (e.g. [this page on the demo site](https://demo.libreread.org/collection/12)), the images of book covers do not appear.

This is because the ``src`` attribute of the ``img`` tag includes a spurious backslash, so that it is set to something like ``"//cover/file-name.png"`` rather than ``"/cover/file-name.png"``

**Comment by kpcyrd** [comment]
I think all remaining cover image paths have been fixed in 0a68c502d4537d1ca9c0b6007321a0e49753edd2.
