### ISSUE TITLE
If docker compose fails it still sets up the systemctl stuff

### ISSUE THREAD

**Issue by jw6jw6jw6** [LibreRead/server#33]
Add verification that docker-compose succeeds and doesn't fail in the install.sh script.

**Comment by kpcyrd** [comment]
I think the first line in that script should be
```
set -e
```

**Comment by kpcyrd** [comment]
I think this has been fixed in 32218f5fb3e7ed453fad6d67fd84f5eb8a94659c. Please reopen the issue if needed.
