### ISSUE TITLE
How do I login?

### ISSUE THREAD

**Issue by egidijus** [LibreRead/server#43]
What is the default password/account?

**Comment by mysticmode** [comment]
Please provide us more detail. Have you self-hosted LibreRead? Did you sign up? What is not working?

We are not doing support for money (at-least not now) only out of our own interest. Thanks.

**Comment by egidijus** [comment]
I cloned the server.
Then I ```docker-compose up -d```
I see that I have a redis container, and I have a libreread container.
When I open up libreread on localhost:8080 I see a login page.

There is no documentation anywhere in this project about what the default credentials are.
I had a look in the libreread container, I could not find a configuration file.
I see that the project is using sqlite, but I have not tried looking in the sqlite db for credentials.

All I want to do, is start using libreread without setting up any email/domains.

**Comment by egidijus** [comment]
Hello,
I was able to sign in after setting the "confirmed" value to 1 in the sqlite db.
No need for domain or SMTP.
Great success!!

**Comment by mysticmode** [comment]
Hey @egidijus Sorry! I was busy the last few days. I couldn't assist you. It's really great that you found a solution.

Also, If you Signup, you don't need the confirmation email token to sign in. You can directly enter your login credentials and it will take you to the home page. Not sure if you faced any problem here.

I have made it like that where you don't need a SMTP Email setup for onboarding, but be careful, If you forgot your password then you will need the email sent with the reset password link.. 

Anyway, I'll improve the on-boarding process as soon as I can. Thanks!
