### ISSUE TITLE
Add development instructions

### ISSUE THREAD

**Issue by gbraad** [LibreRead/server#5]
Add the moment, no instructions are given for the development process. This makes the use/development limited to those that have a good understanding of Golang.

**Comment by gbraad** [comment]
Start of with detailing the way to get dependencies
```
$ go get ./...
```

**Comment by mysticmode** [comment]
Sure, I'll add the dev documentation in the coming days. I'll close this issue once this is done. Thank you!

**Comment by gbraad** [comment]
or a `Makefile` ?

**Comment by mysticmode** [comment]
#20

**Comment by mysticmode** [comment]
I made a pull request on this https://github.com/LibreRead/LibreRead/pull/26
